const SCHEME: u32 = 0x01;
const UNRESERVED: u32 = 0x02;
const GEN_DELIM: u32 = 0x04;
const SUB_DELIM: u32 = 0x08;
const PCHAR_SLASH: u32 = 0x10;
const HEX_DIGIT: u32 = 0x20;
const QUERY: u32 = 0x40;
const FRAGMENT: u32 = 0x40;
const USERINFO: u32 = 0x80;
const IPV6_CHAR: u32 = 0x100;

static CHAR_CAT: [u8; 256] = [0; 256]; // Initialize with appropriate values

fn print_table() {
    println!(
        "// This file is generated by gen_char_category_table. DO NOT EDIT IT BY HAND!\n\
        \n\
        const unsigned short char_cat[256] = {{\n\
        //   .0     .1     .2     .3     .4     .5     .6     .7     .8     .9     .A     .B     .C     .D     .E     .F"
    );

    for y in 0..16 {
        print!(" ");
        for x in 0..16 {
            let offset = y * 16 + x;
            print!(
                " 0x{:03x}{}",
                CHAR_CAT[offset] as u32,
                if offset == 255 { ' ' } else { ',' }
            );
        }
        println!(" // {:01X}0 ... {:01X}F", y, y);
    }
    println!("}};\n");
}

fn main() {
    print_table();
}
