use std::fmt::Write;

#[derive(Debug)]
enum Category {
    Scheme = 0x01,
    Unreserved = 0x02,
    GenDelim = 0x04,
    SubDelim = 0x08,
    PCharSlash = 0x10,
    HexDigit = 0x20,
    Query = 0x40,
    Fragment = 0x40,
    Userinfo = 0x80,
    IPv6Char = 0x100,
}

fn print_table(char_cat: &[u16; 256]) {
    let mut output = String::new();
    writeln!(
        output,
        "// This file is generated by gen_char_category_table. DO NOT EDIT IT BY HAND!\n"
    )
    .unwrap();
    writeln!(output, "const char_cat: [u16; 256] = [").unwrap();
    writeln!(
        output,
        "//   .0     .1     .2     .3     .4     .5     .6     .7     .8     .9     .A     .B     .C     .D     .E     .F"
    )
    .unwrap();

    for y in 0..16 {
        write!(output, " ").unwrap();
        for x in 0..16 {
            let offset = y * 16 + x;
            write!(
                output,
                " 0x{:03x}{}",
                char_cat[offset],
                if offset == 255 { ' ' } else { ',' }
            )
            .unwrap();
        }
        writeln!(output, " // {:01X}0 ... {:01X}F", y, y).unwrap();
    }
    writeln!(output, "];\n").unwrap();

    print!("{}", output);
}

fn main() {
    let char_cat: [u16; 256] = [0; 256]; // Initialize with your actual data
    print_table(&char_cat);
}
