const SCHEME: u16 = 0x01;
const UNRESERVED: u16 = 0x02;
const GEN_DELIM: u16 = 0x04;
const SUB_DELIM: u16 = 0x08;
const PCHAR_SLASH: u16 = 0x10;
const HEX_DIGIT: u16 = 0x20;
const QUERY: u16 = 0x40;
const FRAGMENT: u16 = 0x40; // Same value as QUERY
const USERINFO: u16 = 0x80;
const IPV6_CHAR: u16 = 0x100;

fn print_table(char_cat: &[u16; 256]) {
    println!(
        "// This file is generated by gen_char_category_table. DO NOT EDIT IT BY HAND!\n"
    );
    println!("const char_cat: [u16; 256] = [");
    println!("//   .0     .1     .2     .3     .4     .5     .6     .7     .8     .9     .A     .B     .C     .D     .E     .F");

    for y in 0..16 {
        print!(" ");
        for x in 0..16 {
            let offset = y * 16 + x;
            print!(
                " 0x{:03x}{}",
                char_cat[offset],
                if offset == 255 { ' ' } else { ',' }
            );
        }
        println!(" // {:01X}0 ... {:01X}F", y, y);
    }
    println!("];\n");
}

fn main() {
    let char_cat: [u16; 256] = [0; 256]; // Initialize with your data
    print_table(&char_cat);
}
