; ModuleID = 'gen_char_category_table.c'
source_filename = "gen_char_category_table.c"
target datalayout = "e-m:o-i64:64-i128:128-n32:64-S128"
target triple = "arm64-apple-macosx14.0.0"

%struct.__sFILE = type { i8*, i32, i32, i16, i16, %struct.__sbuf, i32, i8*, i32 (i8*)*, i32 (i8*, i8*, i32)*, i64 (i8*, i64, i32)*, i32 (i8*, i8*, i32)*, %struct.__sbuf, %struct.__sFILEX*, i32, [3 x i8], [1 x i8], %struct.__sbuf, i32, i64 }
%struct.__sFILEX = type opaque
%struct.__sbuf = type { i8*, i32 }

@.str = private unnamed_addr constant [63 x i8] c"0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ\00", align 1
@alnum = constant i8* getelementptr inbounds ([63 x i8], [63 x i8]* @.str, i32 0, i32 0), align 8, !dbg !0
@.str.1 = private unnamed_addr constant [5 x i8] c"-._~\00", align 1
@unreserved = constant i8* getelementptr inbounds ([5 x i8], [5 x i8]* @.str.1, i32 0, i32 0), align 8, !dbg !23
@.str.2 = private unnamed_addr constant [12 x i8] c"!$&'()*+,;=\00", align 1
@subdelim = constant i8* getelementptr inbounds ([12 x i8], [12 x i8]* @.str.2, i32 0, i32 0), align 8, !dbg !28
@char_cat = global [256 x i32] zeroinitializer, align 4, !dbg !30
@.str.3 = private unnamed_addr constant [239 x i8] c"// This file is generated by gen_char_category_table. DO NOT EDIT IT BY HAND!\0A\0Astatic const unsigned short char_cat[256] = {\0A//   .0     .1     .2     .3     .4     .5     .6     .7     .8     .9     .A     .B     .C     .D     .E     .F\0A\00", align 1
@.str.4 = private unnamed_addr constant [10 x i8] c" 0x%03x%c\00", align 1
@.str.5 = private unnamed_addr constant [21 x i8] c" // %01X0 ... %01XF\0A\00", align 1
@.str.6 = private unnamed_addr constant [5 x i8] c"};\0A\0A\00", align 1
@.str.7 = private unnamed_addr constant [4 x i8] c"+-.\00", align 1
@.str.8 = private unnamed_addr constant [8 x i8] c":/?#[]@\00", align 1
@.str.9 = private unnamed_addr constant [5 x i8] c":@/%\00", align 1
@.str.10 = private unnamed_addr constant [11 x i8] c"0123456789\00", align 1
@.str.11 = private unnamed_addr constant [13 x i8] c"abcdefABCDEF\00", align 1
@.str.12 = private unnamed_addr constant [6 x i8] c"/?:@%\00", align 1
@.str.13 = private unnamed_addr constant [3 x i8] c":%\00", align 1
@.str.14 = private unnamed_addr constant [14 x i8] c"abcdefABCDEF:\00", align 1

; Function Attrs: nofree nosync nounwind readnone speculatable willreturn
declare void @llvm.dbg.declare(metadata, metadata, metadata) #0

declare i32 @__swbuf(i32 noundef, %struct.__sFILE* noundef) #1

; Function Attrs: noinline nounwind optnone ssp uwtable
define void @fill(i32 noundef %value, i8* noundef %alnum, i8* noundef %special) #2 !dbg !47 {
entry:
  %value.addr = alloca i32, align 4
  %alnum.addr = alloca i8*, align 8
  %special.addr = alloca i8*, align 8
  store i32 %value, i32* %value.addr, align 4
  call void @llvm.dbg.declare(metadata i32* %value.addr, metadata !51, metadata !DIExpression()), !dbg !52
  store i8* %alnum, i8** %alnum.addr, align 8
  call void @llvm.dbg.declare(metadata i8** %alnum.addr, metadata !53, metadata !DIExpression()), !dbg !54
  store i8* %special, i8** %special.addr, align 8
  call void @llvm.dbg.declare(metadata i8** %special.addr, metadata !55, metadata !DIExpression()), !dbg !56
  br label %for.cond, !dbg !57

for.cond:                                         ; preds = %for.inc, %entry
  %0 = load i8*, i8** %alnum.addr, align 8, !dbg !58
  %1 = load i8, i8* %0, align 1, !dbg !61
  %tobool = icmp ne i8 %1, 0, !dbg !62
  br i1 %tobool, label %for.body, label %for.end, !dbg !62

for.body:                                         ; preds = %for.cond
  %2 = load i32, i32* %value.addr, align 4, !dbg !63
  %3 = load i8*, i8** %alnum.addr, align 8, !dbg !65
  %4 = load i8, i8* %3, align 1, !dbg !66
  %idxprom = zext i8 %4 to i64, !dbg !67
  %arrayidx = getelementptr inbounds [256 x i32], [256 x i32]* @char_cat, i64 0, i64 %idxprom, !dbg !67
  %5 = load i32, i32* %arrayidx, align 4, !dbg !68
  %or = or i32 %5, %2, !dbg !68
  store i32 %or, i32* %arrayidx, align 4, !dbg !68
  br label %for.inc, !dbg !69

for.inc:                                          ; preds = %for.body
  %6 = load i8*, i8** %alnum.addr, align 8, !dbg !70
  %incdec.ptr = getelementptr inbounds i8, i8* %6, i32 1, !dbg !70
  store i8* %incdec.ptr, i8** %alnum.addr, align 8, !dbg !70
  br label %for.cond, !dbg !71, !llvm.loop !72

for.end:                                          ; preds = %for.cond
  br label %for.cond1, !dbg !74

for.cond1:                                        ; preds = %for.inc7, %for.end
  %7 = load i8*, i8** %special.addr, align 8, !dbg !75
  %8 = load i8, i8* %7, align 1, !dbg !78
  %tobool2 = icmp ne i8 %8, 0, !dbg !79
  br i1 %tobool2, label %for.body3, label %for.end9, !dbg !79

for.body3:                                        ; preds = %for.cond1
  %9 = load i32, i32* %value.addr, align 4, !dbg !80
  %10 = load i8*, i8** %special.addr, align 8, !dbg !82
  %11 = load i8, i8* %10, align 1, !dbg !83
  %idxprom4 = zext i8 %11 to i64, !dbg !84
  %arrayidx5 = getelementptr inbounds [256 x i32], [256 x i32]* @char_cat, i64 0, i64 %idxprom4, !dbg !84
  %12 = load i32, i32* %arrayidx5, align 4, !dbg !85
  %or6 = or i32 %12, %9, !dbg !85
  store i32 %or6, i32* %arrayidx5, align 4, !dbg !85
  br label %for.inc7, !dbg !86

for.inc7:                                         ; preds = %for.body3
  %13 = load i8*, i8** %special.addr, align 8, !dbg !87
  %incdec.ptr8 = getelementptr inbounds i8, i8* %13, i32 1, !dbg !87
  store i8* %incdec.ptr8, i8** %special.addr, align 8, !dbg !87
  br label %for.cond1, !dbg !88, !llvm.loop !89

for.end9:                                         ; preds = %for.cond1
  ret void, !dbg !91
}

; Function Attrs: noinline nounwind optnone ssp uwtable
define void @print_table() #2 !dbg !92 {
entry:
  %y = alloca i32, align 4
  %x = alloca i32, align 4
  %offset = alloca i32, align 4
  %call = call i32 (i8*, ...) @printf(i8* noundef getelementptr inbounds ([239 x i8], [239 x i8]* @.str.3, i64 0, i64 0)), !dbg !95
  call void @llvm.dbg.declare(metadata i32* %y, metadata !96, metadata !DIExpression()), !dbg !98
  store i32 0, i32* %y, align 4, !dbg !98
  br label %for.cond, !dbg !99

for.cond:                                         ; preds = %for.inc8, %entry
  %0 = load i32, i32* %y, align 4, !dbg !100
  %cmp = icmp ult i32 %0, 16, !dbg !102
  br i1 %cmp, label %for.body, label %for.end10, !dbg !103

for.body:                                         ; preds = %for.cond
  %call1 = call i32 @putchar(i32 noundef 32), !dbg !104
  call void @llvm.dbg.declare(metadata i32* %x, metadata !106, metadata !DIExpression()), !dbg !108
  store i32 0, i32* %x, align 4, !dbg !108
  br label %for.cond2, !dbg !109

for.cond2:                                        ; preds = %for.inc, %for.body
  %1 = load i32, i32* %x, align 4, !dbg !110
  %cmp3 = icmp ult i32 %1, 16, !dbg !112
  br i1 %cmp3, label %for.body4, label %for.end, !dbg !113

for.body4:                                        ; preds = %for.cond2
  call void @llvm.dbg.declare(metadata i32* %offset, metadata !114, metadata !DIExpression()), !dbg !117
  %2 = load i32, i32* %y, align 4, !dbg !118
  %mul = mul i32 %2, 16, !dbg !119
  %3 = load i32, i32* %x, align 4, !dbg !120
  %add = add i32 %mul, %3, !dbg !121
  store i32 %add, i32* %offset, align 4, !dbg !117
  %4 = load i32, i32* %offset, align 4, !dbg !122
  %idxprom = zext i32 %4 to i64, !dbg !123
  %arrayidx = getelementptr inbounds [256 x i32], [256 x i32]* @char_cat, i64 0, i64 %idxprom, !dbg !123
  %5 = load i32, i32* %arrayidx, align 4, !dbg !123
  %6 = load i32, i32* %offset, align 4, !dbg !124
  %cmp5 = icmp eq i32 %6, 255, !dbg !125
  %7 = zext i1 %cmp5 to i64, !dbg !124
  %cond = select i1 %cmp5, i32 32, i32 44, !dbg !124
  %call6 = call i32 (i8*, ...) @printf(i8* noundef getelementptr inbounds ([10 x i8], [10 x i8]* @.str.4, i64 0, i64 0), i32 noundef %5, i32 noundef %cond), !dbg !126
  br label %for.inc, !dbg !127

for.inc:                                          ; preds = %for.body4
  %8 = load i32, i32* %x, align 4, !dbg !128
  %inc = add i32 %8, 1, !dbg !128
  store i32 %inc, i32* %x, align 4, !dbg !128
  br label %for.cond2, !dbg !129, !llvm.loop !130

for.end:                                          ; preds = %for.cond2
  %9 = load i32, i32* %y, align 4, !dbg !132
  %10 = load i32, i32* %y, align 4, !dbg !133
  %call7 = call i32 (i8*, ...) @printf(i8* noundef getelementptr inbounds ([21 x i8], [21 x i8]* @.str.5, i64 0, i64 0), i32 noundef %9, i32 noundef %10), !dbg !134
  br label %for.inc8, !dbg !135

for.inc8:                                         ; preds = %for.end
  %11 = load i32, i32* %y, align 4, !dbg !136
  %inc9 = add i32 %11, 1, !dbg !136
  store i32 %inc9, i32* %y, align 4, !dbg !136
  br label %for.cond, !dbg !137, !llvm.loop !138

for.end10:                                        ; preds = %for.cond
  %call11 = call i32 (i8*, ...) @printf(i8* noundef getelementptr inbounds ([5 x i8], [5 x i8]* @.str.6, i64 0, i64 0)), !dbg !140
  ret void, !dbg !141
}

declare i32 @printf(i8* noundef, ...) #1

declare i32 @putchar(i32 noundef) #1

; Function Attrs: noinline nounwind optnone ssp uwtable
define i32 @main() #2 !dbg !142 {
entry:
  call void @fill(i32 noundef 1, i8* noundef getelementptr inbounds ([63 x i8], [63 x i8]* @.str, i32 0, i32 0), i8* noundef getelementptr inbounds ([4 x i8], [4 x i8]* @.str.7, i64 0, i64 0)), !dbg !146
  call void @fill(i32 noundef 2, i8* noundef getelementptr inbounds ([63 x i8], [63 x i8]* @.str, i32 0, i32 0), i8* noundef getelementptr inbounds ([5 x i8], [5 x i8]* @.str.1, i32 0, i32 0)), !dbg !147
  call void @fill(i32 noundef 4, i8* noundef getelementptr inbounds ([63 x i8], [63 x i8]* @.str, i32 0, i32 0), i8* noundef getelementptr inbounds ([8 x i8], [8 x i8]* @.str.8, i64 0, i64 0)), !dbg !148
  call void @fill(i32 noundef 8, i8* noundef getelementptr inbounds ([63 x i8], [63 x i8]* @.str, i32 0, i32 0), i8* noundef getelementptr inbounds ([12 x i8], [12 x i8]* @.str.2, i32 0, i32 0)), !dbg !149
  call void @fill(i32 noundef 16, i8* noundef getelementptr inbounds ([63 x i8], [63 x i8]* @.str, i32 0, i32 0), i8* noundef getelementptr inbounds ([5 x i8], [5 x i8]* @.str.9, i64 0, i64 0)), !dbg !150
  call void @fill(i32 noundef 16, i8* noundef getelementptr inbounds ([5 x i8], [5 x i8]* @.str.1, i32 0, i32 0), i8* noundef getelementptr inbounds ([12 x i8], [12 x i8]* @.str.2, i32 0, i32 0)), !dbg !151
  call void @fill(i32 noundef 32, i8* noundef getelementptr inbounds ([11 x i8], [11 x i8]* @.str.10, i64 0, i64 0), i8* noundef getelementptr inbounds ([13 x i8], [13 x i8]* @.str.11, i64 0, i64 0)), !dbg !152
  call void @fill(i32 noundef 64, i8* noundef getelementptr inbounds ([63 x i8], [63 x i8]* @.str, i32 0, i32 0), i8* noundef getelementptr inbounds ([6 x i8], [6 x i8]* @.str.12, i64 0, i64 0)), !dbg !153
  call void @fill(i32 noundef 64, i8* noundef getelementptr inbounds ([5 x i8], [5 x i8]* @.str.1, i32 0, i32 0), i8* noundef getelementptr inbounds ([12 x i8], [12 x i8]* @.str.2, i32 0, i32 0)), !dbg !154
  call void @fill(i32 noundef 128, i8* noundef getelementptr inbounds ([63 x i8], [63 x i8]* @.str, i32 0, i32 0), i8* noundef getelementptr inbounds ([3 x i8], [3 x i8]* @.str.13, i64 0, i64 0)), !dbg !155
  call void @fill(i32 noundef 128, i8* noundef getelementptr inbounds ([5 x i8], [5 x i8]* @.str.1, i32 0, i32 0), i8* noundef getelementptr inbounds ([12 x i8], [12 x i8]* @.str.2, i32 0, i32 0)), !dbg !156
  call void @fill(i32 noundef 256, i8* noundef getelementptr inbounds ([11 x i8], [11 x i8]* @.str.10, i64 0, i64 0), i8* noundef getelementptr inbounds ([14 x i8], [14 x i8]* @.str.14, i64 0, i64 0)), !dbg !157
  call void @print_table(), !dbg !158
  ret i32 0, !dbg !159
}

attributes #0 = { nofree nosync nounwind readnone speculatable willreturn }
attributes #1 = { "frame-pointer"="non-leaf" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="apple-m1" "target-features"="+aes,+crc,+crypto,+dotprod,+fp-armv8,+fp16fml,+fullfp16,+lse,+neon,+ras,+rcpc,+rdm,+sha2,+v8.5a,+zcm,+zcz" }
attributes #2 = { noinline nounwind optnone ssp uwtable "frame-pointer"="non-leaf" "min-legal-vector-width"="0" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="apple-m1" "target-features"="+aes,+crc,+crypto,+dotprod,+fp-armv8,+fp16fml,+fullfp16,+lse,+neon,+ras,+rcpc,+rdm,+sha2,+v8.5a,+zcm,+zcz" }

!llvm.module.flags = !{!35, !36, !37, !38, !39, !40, !41, !42, !43, !44, !45}
!llvm.dbg.cu = !{!2}
!llvm.ident = !{!46}

!0 = !DIGlobalVariableExpression(var: !1, expr: !DIExpression())
!1 = distinct !DIGlobalVariable(name: "alnum", scope: !2, file: !3, line: 10, type: !25, isLocal: false, isDefinition: true)
!2 = distinct !DICompileUnit(language: DW_LANG_C99, file: !3, producer: "clang version 14.0.0 (git@github.com:davsec-lab/typedefextractor.git dfb083149f45185bece93228f47a1ca85d4c12a0)", isOptimized: false, runtimeVersion: 0, emissionKind: FullDebug, enums: !4, retainedTypes: !19, globals: !22, splitDebugInlining: false, nameTableKind: None, sysroot: "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk", sdk: "MacOSX.sdk")
!3 = !DIFile(filename: "gen_char_category_table.c", directory: "/Users/gab/repo/Rust/rustify-validator/src/python/inputs-complex/url.h")
!4 = !{!5}
!5 = !DICompositeType(tag: DW_TAG_enumeration_type, name: "Category", file: !6, line: 4, baseType: !7, size: 32, elements: !8)
!6 = !DIFile(filename: "./url_char_category.h", directory: "/Users/gab/repo/Rust/rustify-validator/src/python/inputs-complex/url.h")
!7 = !DIBasicType(name: "unsigned int", size: 32, encoding: DW_ATE_unsigned)
!8 = !{!9, !10, !11, !12, !13, !14, !15, !16, !17, !18}
!9 = !DIEnumerator(name: "Scheme", value: 1)
!10 = !DIEnumerator(name: "Unreserved", value: 2)
!11 = !DIEnumerator(name: "GenDelim", value: 4)
!12 = !DIEnumerator(name: "SubDelim", value: 8)
!13 = !DIEnumerator(name: "PCharSlash", value: 16)
!14 = !DIEnumerator(name: "HexDigit", value: 32)
!15 = !DIEnumerator(name: "Query", value: 64)
!16 = !DIEnumerator(name: "Fragment", value: 64)
!17 = !DIEnumerator(name: "Userinfo", value: 128)
!18 = !DIEnumerator(name: "IPv6Char", value: 256)
!19 = !{!20, !21}
!20 = !DIBasicType(name: "char", size: 8, encoding: DW_ATE_signed_char)
!21 = !DIBasicType(name: "unsigned char", size: 8, encoding: DW_ATE_unsigned_char)
!22 = !{!0, !23, !28, !30}
!23 = !DIGlobalVariableExpression(var: !24, expr: !DIExpression())
!24 = distinct !DIGlobalVariable(name: "unreserved", scope: !2, file: !3, line: 14, type: !25, isLocal: false, isDefinition: true)
!25 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !26)
!26 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !27, size: 64)
!27 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !20)
!28 = !DIGlobalVariableExpression(var: !29, expr: !DIExpression())
!29 = distinct !DIGlobalVariable(name: "subdelim", scope: !2, file: !3, line: 15, type: !25, isLocal: false, isDefinition: true)
!30 = !DIGlobalVariableExpression(var: !31, expr: !DIExpression())
!31 = distinct !DIGlobalVariable(name: "char_cat", scope: !2, file: !3, line: 7, type: !32, isLocal: false, isDefinition: true)
!32 = !DICompositeType(tag: DW_TAG_array_type, baseType: !7, size: 8192, elements: !33)
!33 = !{!34}
!34 = !DISubrange(count: 256)
!35 = !{i32 2, !"SDK Version", [2 x i32] [i32 14, i32 4]}
!36 = !{i32 7, !"Dwarf Version", i32 4}
!37 = !{i32 2, !"Debug Info Version", i32 3}
!38 = !{i32 1, !"wchar_size", i32 4}
!39 = !{i32 1, !"branch-target-enforcement", i32 0}
!40 = !{i32 1, !"sign-return-address", i32 0}
!41 = !{i32 1, !"sign-return-address-all", i32 0}
!42 = !{i32 1, !"sign-return-address-with-bkey", i32 0}
!43 = !{i32 7, !"PIC Level", i32 2}
!44 = !{i32 7, !"uwtable", i32 1}
!45 = !{i32 7, !"frame-pointer", i32 1}
!46 = !{!"clang version 14.0.0 (git@github.com:davsec-lab/typedefextractor.git dfb083149f45185bece93228f47a1ca85d4c12a0)"}
!47 = distinct !DISubprogram(name: "fill", scope: !3, file: !3, line: 17, type: !48, scopeLine: 18, flags: DIFlagPrototyped, spFlags: DISPFlagDefinition, unit: !2, retainedNodes: !50)
!48 = !DISubroutineType(types: !49)
!49 = !{null, !7, !26, !26}
!50 = !{}
!51 = !DILocalVariable(name: "value", arg: 1, scope: !47, file: !3, line: 17, type: !7)
!52 = !DILocation(line: 17, column: 20, scope: !47)
!53 = !DILocalVariable(name: "alnum", arg: 2, scope: !47, file: !3, line: 17, type: !26)
!54 = !DILocation(line: 17, column: 39, scope: !47)
!55 = !DILocalVariable(name: "special", arg: 3, scope: !47, file: !3, line: 17, type: !26)
!56 = !DILocation(line: 17, column: 58, scope: !47)
!57 = !DILocation(line: 19, column: 2, scope: !47)
!58 = !DILocation(line: 19, column: 8, scope: !59)
!59 = distinct !DILexicalBlock(scope: !60, file: !3, line: 19, column: 2)
!60 = distinct !DILexicalBlock(scope: !47, file: !3, line: 19, column: 2)
!61 = !DILocation(line: 19, column: 7, scope: !59)
!62 = !DILocation(line: 19, column: 2, scope: !60)
!63 = !DILocation(line: 21, column: 42, scope: !64)
!64 = distinct !DILexicalBlock(scope: !59, file: !3, line: 20, column: 2)
!65 = !DILocation(line: 21, column: 30, scope: !64)
!66 = !DILocation(line: 21, column: 29, scope: !64)
!67 = !DILocation(line: 21, column: 3, scope: !64)
!68 = !DILocation(line: 21, column: 39, scope: !64)
!69 = !DILocation(line: 22, column: 2, scope: !64)
!70 = !DILocation(line: 19, column: 14, scope: !59)
!71 = !DILocation(line: 19, column: 2, scope: !59)
!72 = distinct !{!72, !62, !73}
!73 = !DILocation(line: 22, column: 2, scope: !60)
!74 = !DILocation(line: 24, column: 2, scope: !47)
!75 = !DILocation(line: 24, column: 8, scope: !76)
!76 = distinct !DILexicalBlock(scope: !77, file: !3, line: 24, column: 2)
!77 = distinct !DILexicalBlock(scope: !47, file: !3, line: 24, column: 2)
!78 = !DILocation(line: 24, column: 7, scope: !76)
!79 = !DILocation(line: 24, column: 2, scope: !77)
!80 = !DILocation(line: 26, column: 44, scope: !81)
!81 = distinct !DILexicalBlock(scope: !76, file: !3, line: 25, column: 2)
!82 = !DILocation(line: 26, column: 30, scope: !81)
!83 = !DILocation(line: 26, column: 29, scope: !81)
!84 = !DILocation(line: 26, column: 3, scope: !81)
!85 = !DILocation(line: 26, column: 41, scope: !81)
!86 = !DILocation(line: 27, column: 2, scope: !81)
!87 = !DILocation(line: 24, column: 16, scope: !76)
!88 = !DILocation(line: 24, column: 2, scope: !76)
!89 = distinct !{!89, !79, !90}
!90 = !DILocation(line: 27, column: 2, scope: !77)
!91 = !DILocation(line: 28, column: 1, scope: !47)
!92 = distinct !DISubprogram(name: "print_table", scope: !3, file: !3, line: 31, type: !93, scopeLine: 32, spFlags: DISPFlagDefinition, unit: !2, retainedNodes: !50)
!93 = !DISubroutineType(types: !94)
!94 = !{null}
!95 = !DILocation(line: 33, column: 2, scope: !92)
!96 = !DILocalVariable(name: "y", scope: !97, file: !3, line: 39, type: !7)
!97 = distinct !DILexicalBlock(scope: !92, file: !3, line: 39, column: 2)
!98 = !DILocation(line: 39, column: 15, scope: !97)
!99 = !DILocation(line: 39, column: 6, scope: !97)
!100 = !DILocation(line: 39, column: 20, scope: !101)
!101 = distinct !DILexicalBlock(scope: !97, file: !3, line: 39, column: 2)
!102 = !DILocation(line: 39, column: 21, scope: !101)
!103 = !DILocation(line: 39, column: 2, scope: !97)
!104 = !DILocation(line: 41, column: 3, scope: !105)
!105 = distinct !DILexicalBlock(scope: !101, file: !3, line: 40, column: 2)
!106 = !DILocalVariable(name: "x", scope: !107, file: !3, line: 42, type: !7)
!107 = distinct !DILexicalBlock(scope: !105, file: !3, line: 42, column: 3)
!108 = !DILocation(line: 42, column: 16, scope: !107)
!109 = !DILocation(line: 42, column: 7, scope: !107)
!110 = !DILocation(line: 42, column: 21, scope: !111)
!111 = distinct !DILexicalBlock(scope: !107, file: !3, line: 42, column: 3)
!112 = !DILocation(line: 42, column: 22, scope: !111)
!113 = !DILocation(line: 42, column: 3, scope: !107)
!114 = !DILocalVariable(name: "offset", scope: !115, file: !3, line: 44, type: !116)
!115 = distinct !DILexicalBlock(scope: !111, file: !3, line: 43, column: 3)
!116 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !7)
!117 = !DILocation(line: 44, column: 19, scope: !115)
!118 = !DILocation(line: 44, column: 28, scope: !115)
!119 = !DILocation(line: 44, column: 29, scope: !115)
!120 = !DILocation(line: 44, column: 33, scope: !115)
!121 = !DILocation(line: 44, column: 32, scope: !115)
!122 = !DILocation(line: 45, column: 33, scope: !115)
!123 = !DILocation(line: 45, column: 24, scope: !115)
!124 = !DILocation(line: 45, column: 43, scope: !115)
!125 = !DILocation(line: 45, column: 49, scope: !115)
!126 = !DILocation(line: 45, column: 4, scope: !115)
!127 = !DILocation(line: 46, column: 3, scope: !115)
!128 = !DILocation(line: 42, column: 27, scope: !111)
!129 = !DILocation(line: 42, column: 3, scope: !111)
!130 = distinct !{!130, !113, !131}
!131 = !DILocation(line: 46, column: 3, scope: !107)
!132 = !DILocation(line: 47, column: 35, scope: !105)
!133 = !DILocation(line: 47, column: 38, scope: !105)
!134 = !DILocation(line: 47, column: 3, scope: !105)
!135 = !DILocation(line: 48, column: 2, scope: !105)
!136 = !DILocation(line: 39, column: 26, scope: !101)
!137 = !DILocation(line: 39, column: 2, scope: !101)
!138 = distinct !{!138, !103, !139}
!139 = !DILocation(line: 48, column: 2, scope: !97)
!140 = !DILocation(line: 49, column: 2, scope: !92)
!141 = !DILocation(line: 50, column: 1, scope: !92)
!142 = distinct !DISubprogram(name: "main", scope: !3, file: !3, line: 53, type: !143, scopeLine: 54, spFlags: DISPFlagDefinition, unit: !2, retainedNodes: !50)
!143 = !DISubroutineType(types: !144)
!144 = !{!145}
!145 = !DIBasicType(name: "int", size: 32, encoding: DW_ATE_signed)
!146 = !DILocation(line: 55, column: 2, scope: !142)
!147 = !DILocation(line: 57, column: 2, scope: !142)
!148 = !DILocation(line: 59, column: 2, scope: !142)
!149 = !DILocation(line: 61, column: 2, scope: !142)
!150 = !DILocation(line: 63, column: 2, scope: !142)
!151 = !DILocation(line: 64, column: 2, scope: !142)
!152 = !DILocation(line: 66, column: 2, scope: !142)
!153 = !DILocation(line: 68, column: 2, scope: !142)
!154 = !DILocation(line: 69, column: 2, scope: !142)
!155 = !DILocation(line: 71, column: 2, scope: !142)
!156 = !DILocation(line: 72, column: 2, scope: !142)
!157 = !DILocation(line: 74, column: 2, scope: !142)
!158 = !DILocation(line: 76, column: 2, scope: !142)
!159 = !DILocation(line: 77, column: 1, scope: !142)
